### ISSUE TITLE
Please further describe cron

### ISSUE THREAD

**Issue by parhamr** [anchor/fleet-magento-docs#38]
As of revision c6b2cbe3d39dd756c5bcab7d121c0c04a364cf8b, file `docs/configuring-magento-for-fleet/customisation.md`, the “Providing a crontab” section does not adequately explain the default Magento cron behaviors (e.g. `cron.sh`) on Fleet. Please add:
- default run interval
- default host that executes the Magento cron

**Comment by paddur** [comment]
Would also be nice to have read access to the cron fragment for troubleshooting.
