### ISSUE TITLE
Please describe the Redis integration

### ISSUE THREAD

**Issue by parhamr** [anchor/fleet-magento-docs#40]
Which PHP client library (and version) is used to communicate with Redis? What is the default timeout?

I presently do not see this information covered by these docs:
- http://docs.anchorfleet.com/fleet-magento-1/faq/software-versions/
- http://docs.anchorfleet.com/fleet-magento-1/configuring-magento-for-fleet/configure-cache-and-sessions/

**Comment by privatesmith** [comment]
The reason the library used to connect to Redis is not documented is because we don't currently supply any such library.

Magento bundles Credis (see lib/Credis), which is what will generally be used for the redis connection.
