### ISSUE TITLE
How should a customer handled failed releases?

### ISSUE THREAD

**Issue by parhamr** [anchor/fleet-magento-docs#48]
Given this environment state, how should I handle failed release `e99215e`? [This documentation section references a failed deployment](http://docs.anchorfleet.com/fleet-magento-1/what-is-fleet/what-is-fleet/#deploying-code) but it does not explain what to do about this outcome.

```
$ fleet env describe prod
----------------  -------------------------
name              prod
status            RUNNING
whitelist         allow-all
ssl certificate   redacted
created           2015-08-21 06:24:11+00:00
updated           2015-09-29 02:13:36+00:00
recycling         ON
solr              OFF
tracked branches  fleet-deploy
previous release  ef9e450
autoscaling min   4
autoscaling max   14
ha                ON
----------------  -------------------------

Releases:
name     status      loaded                     updated                      frontends
-------  ----------  -------------------------  -------------------------  -----------
e99215e  FAILED      2015-09-29 03:41:08+00:00  2015-09-29 03:49:02+00:00            0
e2b520d  * ACTIVE *  2015-09-24 04:23:11+00:00  2015-09-25 19:12:33+00:00            4
ef9e450  RUNNING     2015-09-23 23:10:27+00:00  2015-09-25 19:12:33+00:00            4

Endpoints:
--------  ---------------------------------
admin     admin.prod.redacted.f.nchr.io
adminssh  adminssh.prod.redacted.f.nchr.io
www       www.prod.redacted.f.nchr.io
--------  ---------------------------------
```

Do I try to activate the release again? Do I have to fully unload that release and start my deployment routines?

Please explain.

**Comment by parhamr** [comment]
Related: I do not see a full listing of all possible states of a release and what each state means. This seems like information that would support the above issue.

**Comment by cosmopetrich** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;hsUVFMGt&#x2F;281-parse-customer-issues-and-prs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Parse customer issues and PRs</a>

**Comment by cosmopetrich** [comment]
Hi @parhamr. Sorry for the delay in getting to this, we'll take a look and get back to you shortly.
